// On-device Piper TTS engine using react-native-sherpa-onnx-offline-tts.
// Real-time, offline, no server. Assets are pre-bundled in the APK.
import { Asset } from 'expo-asset';
import Constants from 'expo-constants';
import * as Device from 'expo-device';
import * as FileSystem from 'expo-file-system/legacy';
import { unzipSync } from 'fflate';
import { NativeModules, Platform } from 'react-native';
import { Buffer } from 'buffer';
import { PIPER_ASSETS } from './piperAssets';
import { getSherpaTTS, isPiperAvailable } from './sherpaPiper';
// Runtime config generated by scripts/prepare_piper_model.py from the
// model's .onnx.json. Single source of truth for the sample rate.
// eslint-disable-next-line @typescript-eslint/no-require-imports
const PIPER_CONFIG: { sample_rate: number; language?: string; voice?: string; n_speakers?: number } =
  require('../../assets/piper/piper-config.json');
const PIPER_SAMPLE_RATE = PIPER_CONFIG.sample_rate || 22050;

let initPromise: Promise<boolean> | null = null;
let ready = false;
let lastError: string | null = null;
let lastStep: string = 'idle';

const DEST_DIR = `${FileSystem.documentDirectory}piper`;
const TRACE_FILE = `${FileSystem.documentDirectory}piper-trace.log`;

// ─── Native trace file path (used by Kotlin patches) ─────────────────────
// On Android, FileSystem.documentDirectory == /data/data/<pkg>/files which
// is identical to context.filesDir on the native side. The patched Kotlin
// modules (TTSManagerModule, AudioPlayerTrace) write to filesDir/piper-trace.log.
// That's the SAME file as our JS-side TRACE_FILE — so [native] and [audio]
// lines interleave naturally with the [js] lines below.

// Crash-resilient logger: writes every step to disk so that, even if the
// process is killed by a native JNI fault, the next launch can show the user
// EXACTLY where the previous run died (no logcat needed).
async function trace(step: string, info: string = ''): Promise<void> {
  lastStep = step;
  const line = `[${new Date().toISOString()}] [js] ${step}${info ? ' :: ' + info : ''}\n`;
  try {
    const existing = (await FileSystem.getInfoAsync(TRACE_FILE)).exists
      ? await FileSystem.readAsStringAsync(TRACE_FILE)
      : '';
    // Cap at 100 KB (we have many more entries now with granular logging).
    const truncated = existing.length > 100_000 ? existing.slice(-50_000) : existing;
    await FileSystem.writeAsStringAsync(TRACE_FILE, truncated + line);
  } catch {
    /* ignore */
  }
  console.log(`[Piper trace] ${line.trim()}`);
}

export async function readPiperTrace(): Promise<string> {
  try {
    const info = await FileSystem.getInfoAsync(TRACE_FILE);
    if (!info.exists) return '(nessun trace registrato)';
    return await FileSystem.readAsStringAsync(TRACE_FILE);
  } catch (e: any) {
    return `(impossibile leggere trace: ${e?.message || e})`;
  }
}

export async function clearPiperTrace(): Promise<void> {
  try { await FileSystem.deleteAsync(TRACE_FILE, { idempotent: true }); } catch { /* ignore */ }
}

export function getPiperDiagnostics() {
  return { ready, lastError, lastStep, available: isPiperAvailable() };
}

// ─── System info dump for diagnostics ────────────────────────────────────
async function logSystemInfo(): Promise<void> {
  try {
    const brand = Device.brand || 'unknown';
    const modelName = Device.modelName || 'unknown';
    const osName = Device.osName || Platform.OS;
    const osVersion = Device.osVersion || 'unknown';
    const totalMemMB = Math.round((Device.totalMemory || 0) / (1024 * 1024));
    const isDevice = Device.isDevice;
    const supportedCpuArchitectures = (Device as any).supportedCpuArchitectures?.join(',') || 'unknown';
    await trace('sysinfo',
      `brand=${brand} model=${modelName} os=${osName}/${osVersion} mem=${totalMemMB}MB isDevice=${isDevice} arch=${supportedCpuArchitectures}`);
    await trace('sysinfo.expo',
      `expo=${Constants.expoConfig?.version || '?'} sdk=${Constants.expoConfig?.sdkVersion || '?'}`);
    await trace('sysinfo.paths',
      `docDir=${FileSystem.documentDirectory} cacheDir=${FileSystem.cacheDirectory}`);
  } catch (e: any) {
    await trace('sysinfo.err', `${e?.message || e}`);
  }
}

// ─── File integrity helpers (used by initEngine + runFullDiagnostics) ────
async function verifyOnnxMagic(modelPath: string): Promise<{ ok: boolean; hex: string; sizeBytes: number }> {
  try {
    const info = await FileSystem.getInfoAsync(modelPath, { size: true } as any);
    if (!info.exists) return { ok: false, hex: '(missing)', sizeBytes: 0 };
    const head = await FileSystem.readAsStringAsync(modelPath, {
      encoding: FileSystem.EncodingType.Base64, length: 16, position: 0,
    } as any);
    const bytes = Array.from(Buffer.from(head, 'base64'));
    const hex = bytes.map(b => b.toString(16).padStart(2, '0')).join(' ');
    // ONNX is a protobuf — first byte should be 0x08 (field 1, varint = ir_version)
    return { ok: bytes[0] === 0x08, hex, sizeBytes: (info as any).size || 0 };
  } catch (e: any) {
    return { ok: false, hex: `(err: ${e?.message || e})`, sizeBytes: 0 };
  }
}

async function countDirEntries(dirPath: string): Promise<number> {
  try {
    const entries = await FileSystem.readDirectoryAsync(dirPath);
    return entries.length;
  } catch {
    return -1;
  }
}

async function ensureDir(path: string): Promise<void> {
  const info = await FileSystem.getInfoAsync(path);
  if (!info.exists) {
    await FileSystem.makeDirectoryAsync(path, { intermediates: true });
  }
}

async function copyAsset(modId: number, destName: string): Promise<string> {
  const dest = `${DEST_DIR}/${destName}`;
  const info = await FileSystem.getInfoAsync(dest);
  if (info.exists) {
    await trace(`copy.${destName}.skip`, 'already exists');
    return dest;
  }
  await trace(`copy.${destName}.resolve`, 'Asset.fromModule()...');
  const asset = Asset.fromModule(modId);
  await trace(`copy.${destName}.download`, 'asset.downloadAsync()...');
  await asset.downloadAsync();
  const src = asset.localUri || asset.uri;
  if (!src) throw new Error(`Asset ${destName} ha localUri vuoto`);
  await trace(`copy.${destName}.src`, `src=${src.slice(0, 120)}`);
  await trace(`copy.${destName}.copy`, `-> ${dest.slice(0, 120)}`);
  await FileSystem.copyAsync({ from: src, to: dest });
  await trace(`copy.${destName}.ok`, 'done');
  return dest;
}

async function unzipEspeak(modId: number): Promise<string> {
  const dataDir = `${DEST_DIR}/espeak-ng-data`;
  const marker = `${DEST_DIR}/.espeak-ready`;
  await trace('espeak.check', 'checking for ready marker...');
  const dirInfo = await FileSystem.getInfoAsync(dataDir);
  const markerInfo = await FileSystem.getInfoAsync(marker);
  if (dirInfo.exists && dirInfo.isDirectory && markerInfo.exists) {
    const entryCount = await countDirEntries(dataDir);
    await trace('espeak.skip', `already extracted, entries=${entryCount}`);
    return dataDir;
  }
  if (dirInfo.exists) {
    await trace('espeak.cleanup', 'partial dir detected, deleting...');
    try { await FileSystem.deleteAsync(dataDir, { idempotent: true }); } catch { /* ignore */ }
  }

  await trace('espeak.resolve', 'Asset.fromModule()...');
  const asset = Asset.fromModule(modId);
  await asset.downloadAsync();
  const src = asset.localUri || asset.uri;
  if (!src) throw new Error('espeak-ng-data.bin: localUri vuoto');
  await trace('espeak.src', `src=${src.slice(0, 120)}`);

  await trace('espeak.read.b64', 'reading zip as base64...');
  const b64 = await FileSystem.readAsStringAsync(src, { encoding: FileSystem.EncodingType.Base64 });
  await trace('espeak.read.b64.ok', `len=${b64.length} bytes (base64)`);

  await trace('espeak.decode', 'base64 -> Uint8Array...');
  const bytes = new Uint8Array(Buffer.from(b64, 'base64'));
  await trace('espeak.decode.ok', `size=${bytes.length} bytes`);

  // Verify ZIP magic
  const zipMagic = `${bytes[0].toString(16)} ${bytes[1].toString(16)} ${bytes[2].toString(16)} ${bytes[3].toString(16)}`;
  await trace('espeak.zip.magic', `head=${zipMagic} (expect 50 4b 3 4 = PK\\x03\\x04)`);

  await trace('espeak.unzip', 'unzipSync()...');
  const entries = unzipSync(bytes);
  const totalEntries = Object.keys(entries).length;
  await trace('espeak.unzip.ok', `${totalEntries} entries`);

  let count = 0;
  for (const [name, data] of Object.entries(entries)) {
    const fullPath = `${DEST_DIR}/${name}`;
    if (name.endsWith('/') || data.length === 0) {
      await ensureDir(fullPath);
      continue;
    }
    const parent = fullPath.replace(/\/[^/]+$/, '');
    await ensureDir(parent);
    const out64 = Buffer.from(data).toString('base64');
    await FileSystem.writeAsStringAsync(fullPath, out64, { encoding: FileSystem.EncodingType.Base64 });
    count += 1;
    if (count % 50 === 0) {
      await trace('espeak.write.progress', `${count}/${totalEntries}`);
      await new Promise<void>((r) => setTimeout(r, 0));
    }
  }
  await FileSystem.writeAsStringAsync(marker, String(count), { encoding: FileSystem.EncodingType.UTF8 });
  await trace('espeak.complete', `wrote ${count} files, marker created`);
  return dataDir;
}

function stripFilePrefix(p: string): string {
  return p.startsWith('file://') ? p.slice(7) : p;
}

export async function initEngine(): Promise<boolean> {
  if (initPromise) return initPromise;
  initPromise = (async () => {
    await trace('==INIT.START==', `sample_rate=${PIPER_SAMPLE_RATE}`);
    await logSystemInfo();

    if (!isPiperAvailable()) {
      lastError = 'Modulo nativo Sherpa non disponibile (anteprima Expo Go)';
      await trace('check-native', 'FAIL: TTSManager non in NativeModules');
      return false;
    }
    const nm: any = (NativeModules as any).TTSManager;
    await trace('check-native', `OK module=${typeof nm} hasInit=${typeof nm?.initializeTTS}`);

    try {
      await trace('mkdir', `path=${DEST_DIR}`);
      await ensureDir(DEST_DIR);
      await trace('mkdir.ok', 'directory ensured');

      await trace('==PHASE.1==', 'copy beppe.onnx');
      const modelPathU = await copyAsset(PIPER_ASSETS.model, 'beppe.onnx');
      const modelStat = await FileSystem.getInfoAsync(modelPathU, { size: true } as any);
      await trace('phase1.done', `path=${modelPathU} size=${(modelStat as any).size || 0}B`);

      await trace('==PHASE.2==', 'copy tokens.txt');
      const tokensPathU = await copyAsset(PIPER_ASSETS.tokens, 'tokens.txt');
      const tokensStat = await FileSystem.getInfoAsync(tokensPathU, { size: true } as any);
      await trace('phase2.done', `path=${tokensPathU} size=${(tokensStat as any).size || 0}B`);

      await trace('==PHASE.3==', 'extract espeak-ng-data (può richiedere 10-30s)');
      const dataDirPathU = await unzipEspeak(PIPER_ASSETS.espeakZip);
      const dataDirStat = await FileSystem.getInfoAsync(dataDirPathU);
      const espeakCount = await countDirEntries(dataDirPathU);
      await trace('phase3.done', `path=${dataDirPathU} isDir=${dataDirStat.isDirectory} entries=${espeakCount}`);

      const modelPath = stripFilePrefix(modelPathU);
      const tokensPath = stripFilePrefix(tokensPathU);
      const dataDirPath = stripFilePrefix(dataDirPathU);

      // Verify ONNX magic
      await trace('==PHASE.4==', 'verify ONNX magic bytes');
      const magic = await verifyOnnxMagic(modelPathU);
      await trace('phase4.magic', `head=${magic.hex} size=${magic.sizeBytes}B validMagic=${magic.ok}`);
      if (!magic.ok) {
        await trace('phase4.WARN', 'first byte != 0x08 (not standard protobuf — but might still be valid ONNX with custom export)');
      }

      // Sanity checks
      await trace('==PHASE.5==', 'final sanity checks');
      if (!modelStat.exists || !(modelStat as any).size) {
        throw new Error(`modello mancante o vuoto: ${modelPath}`);
      }
      if (!tokensStat.exists || !(tokensStat as any).size) {
        throw new Error(`tokens.txt mancante o vuoto: ${tokensPath}`);
      }
      if (!dataDirStat.exists || !dataDirStat.isDirectory) {
        throw new Error(`espeak-ng-data non è una directory: ${dataDirPath}`);
      }
      if (espeakCount < 10) {
        throw new Error(`espeak-ng-data ha solo ${espeakCount} file (estrazione fallita?)`);
      }
      // Check for canonical espeak files
      const espeakEntries = await FileSystem.readDirectoryAsync(dataDirPathU);
      const hasPhontab = espeakEntries.includes('phontab');
      const hasPhonindex = espeakEntries.includes('phonindex');
      const hasLang = espeakEntries.includes('lang');
      await trace('phase5.espeak.files',
        `phontab=${hasPhontab} phonindex=${hasPhonindex} lang=${hasLang} first10=${espeakEntries.slice(0, 10).join(',')}`);
      if (!hasPhontab || !hasPhonindex) {
        await trace('phase5.WARN', 'missing canonical espeak files (phontab/phonindex)');
      }

      await trace('==PHASE.6==', 'invoke native initializeTTS');
      await trace('phase6.args',
        `sr=${PIPER_SAMPLE_RATE} ch=1 modelPath=${modelPath} tokensPath=${tokensPath} dataDirPath=${dataDirPath}`);
      const tts = getSherpaTTS()!;
      const cfg = { modelPath, tokensPath, dataDirPath };

      await new Promise<void>((resolve, reject) => {
        try {
          const native: any = (NativeModules as any).TTSManager;
          let ret: any;
          if (native && typeof native.initializeTTS === 'function') {
            ret = native.initializeTTS(PIPER_SAMPLE_RATE, 1, JSON.stringify(cfg));
          } else {
            ret = (tts as any).initialize(JSON.stringify(cfg));
          }
          if (ret && typeof ret.then === 'function') {
            ret.then(() => resolve(), (err: any) => reject(err));
          } else {
            setTimeout(() => resolve(), 50);
          }
        } catch (err) {
          reject(err);
        }
      });
      await trace('phase6.done', 'native initializeTTS returned without JNI exception');

      ready = true;
      lastError = null;
      await trace('==INIT.READY==', 'TTS engine pronto');
      return true;
    } catch (e: any) {
      ready = false;
      lastError = `${lastStep}: ${e?.message || String(e)}`;
      await trace('==INIT.ERROR==', `at step=${lastStep}: ${e?.message || String(e)}`);
      return false;
    }
  })();
  return initPromise;
}

// ─── Diagnostic-only function (does NOT actually init TTS) ───────────────
// Performs all the file checks and reports a status object that can be
// rendered in the Settings panel. Useful for troubleshooting WITHOUT
// triggering a potentially-crashing native call.
export type DiagnosticItem = { name: string; ok: boolean; detail: string };

export async function runFullDiagnostics(): Promise<DiagnosticItem[]> {
  const results: DiagnosticItem[] = [];
  const push = async (name: string, ok: boolean, detail: string) => {
    results.push({ name, ok, detail });
    await trace(`diag.${name}`, `ok=${ok} ${detail}`);
  };

  await trace('==DIAGNOSTICS.START==', '');

  // 1. Platform
  await push('Platform',
    Platform.OS === 'android' || Platform.OS === 'ios',
    `OS=${Platform.OS} ver=${Platform.Version}`);

  // 2. Device info
  await push('Device',
    !!Device.brand,
    `${Device.brand || '?'} ${Device.modelName || '?'} mem=${Math.round((Device.totalMemory || 0) / (1024 * 1024))}MB`);

  // 3. Native module presence
  const nm: any = (NativeModules as any).TTSManager;
  await push('NativeModule',
    !!nm && typeof nm.initializeTTS === 'function',
    `TTSManager=${!!nm} hasInit=${typeof nm?.initializeTTS}`);

  // 4. DEST_DIR exists
  const destInfo = await FileSystem.getInfoAsync(DEST_DIR);
  await push('DestDir', destInfo.exists, `${DEST_DIR} exists=${destInfo.exists}`);

  // 5. Model file
  const modelPath = `${DEST_DIR}/beppe.onnx`;
  const modelInfo = await FileSystem.getInfoAsync(modelPath, { size: true } as any);
  const modelSize = (modelInfo as any).size || 0;
  await push('Model', modelInfo.exists && modelSize > 1_000_000,
    `${modelPath} exists=${modelInfo.exists} size=${modelSize}B (${(modelSize / 1024 / 1024).toFixed(1)}MB)`);

  // 6. ONNX magic
  if (modelInfo.exists) {
    const magic = await verifyOnnxMagic(modelPath);
    await push('OnnxMagic', magic.ok, `head=${magic.hex} (valid=${magic.ok})`);
  } else {
    await push('OnnxMagic', false, '(skipped: model not copied yet)');
  }

  // 7. Tokens file
  const tokensPath = `${DEST_DIR}/tokens.txt`;
  const tokensInfo = await FileSystem.getInfoAsync(tokensPath, { size: true } as any);
  await push('Tokens', tokensInfo.exists && (tokensInfo as any).size > 0,
    `${tokensPath} exists=${tokensInfo.exists} size=${(tokensInfo as any).size || 0}B`);

  // 8. Espeak directory + content
  const espeakDir = `${DEST_DIR}/espeak-ng-data`;
  const espeakInfo = await FileSystem.getInfoAsync(espeakDir);
  await push('EspeakDir', espeakInfo.exists && espeakInfo.isDirectory,
    `${espeakDir} exists=${espeakInfo.exists} isDir=${espeakInfo.isDirectory}`);

  if (espeakInfo.exists && espeakInfo.isDirectory) {
    const entries = await FileSystem.readDirectoryAsync(espeakDir);
    const hasPhontab = entries.includes('phontab');
    const hasPhonindex = entries.includes('phonindex');
    await push('EspeakFiles',
      entries.length >= 10 && hasPhontab && hasPhonindex,
      `entries=${entries.length} phontab=${hasPhontab} phonindex=${hasPhonindex}`);
  } else {
    await push('EspeakFiles', false, '(skipped: dir missing)');
  }

  // 9. Trace file size
  const traceInfo = await FileSystem.getInfoAsync(TRACE_FILE, { size: true } as any);
  await push('TraceFile', true,
    `${TRACE_FILE} exists=${traceInfo.exists} size=${(traceInfo as any).size || 0}B`);

  // 10. Engine state
  await push('EngineState', true,
    `ready=${ready} lastError=${lastError || 'none'} lastStep=${lastStep}`);

  await trace('==DIAGNOSTICS.END==', `${results.length} checks ${results.filter(r => r.ok).length} ok`);
  return results;
}

export function isPiperReady(): boolean {
  return ready;
}

// Sanitize a sentence before sending to Sherpa-ONNX.
function sanitizeForPiper(raw: string): string {
  return raw
    .replace(/(\p{L})-(\p{L})/gu, '$1 $2')
    .replace(/\s*[—–]\s*/g, ', ')
    .replace(/[\u0000-\u001F\u007F]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

export async function speakSentence(text: string, lengthScale: number): Promise<void> {
  const tts = getSherpaTTS();
  if (!tts || !ready) {
    await trace('speak.skip', 'Piper not available');
    throw new Error('Piper not available');
  }
  const speed = Math.max(0.5, Math.min(2.0, 1 / lengthScale));
  const clean = sanitizeForPiper(text);
  if (!clean) {
    await trace('speak.skip', 'empty after sanitize');
    return;
  }
  const preview = clean.slice(0, 80);
  try {
    await trace('speak.start', `len=${clean.length} speed=${speed.toFixed(2)} preview="${preview}"`);
    await tts.generateAndPlay(clean, 0, speed);
    await trace('speak.end', 'OK');
  } catch (e: any) {
    await trace('speak.error', `${e?.message || String(e)}`);
    throw e;
  }
}

export async function stopSpeak(): Promise<void> {
  const tts = getSherpaTTS();
  if (!tts) return;
  try {
    await trace('stop.call', 'deinitialize');
    await tts.deinitialize();
    await trace('stop.call', 'OK');
  } catch (e: any) {
    await trace('stop.call', `err: ${e?.message || e}`);
  }
  ready = false;
  initPromise = null;
  initEngine();
}

export const piperPlatformOk = Platform.OS === 'android' || Platform.OS === 'ios';
