// On-device Piper TTS engine using react-native-sherpa-onnx-offline-tts.
// Real-time, offline, no server. Assets are pre-bundled in the APK.
import { Asset } from 'expo-asset';
import Constants from 'expo-constants';
import * as Device from 'expo-device';
import * as FileSystem from 'expo-file-system/legacy';
import { unzipSync } from 'fflate';
import { NativeModules, Platform } from 'react-native';
import { Buffer } from 'buffer';
import { PIPER_ASSETS } from './piperAssets';
import { getSherpaTTS, isPiperAvailable } from './sherpaPiper';
// Runtime config generated by scripts/prepare_piper_model.py from the
// model's .onnx.json. Single source of truth for the sample rate.
// eslint-disable-next-line @typescript-eslint/no-require-imports
const PIPER_CONFIG: { sample_rate: number; language?: string; voice?: string; n_speakers?: number } =
  require('../../assets/piper/piper-config.json');
const PIPER_SAMPLE_RATE = PIPER_CONFIG.sample_rate || 22050;

let initPromise: Promise<boolean> | null = null;
let ready = false;
let lastError: string | null = null;
let lastStep: string = 'idle';

const DEST_DIR = `${FileSystem.documentDirectory}piper`;
const TRACE_FILE = `${FileSystem.documentDirectory}piper-trace.log`;

// ─── Native trace file path (used by Kotlin patches) ─────────────────────
// On Android, FileSystem.documentDirectory == /data/data/<pkg>/files which
// is identical to context.filesDir on the native side. The patched Kotlin
// modules (TTSManagerModule, AudioPlayerTrace) write to filesDir/piper-trace.log.
// That's the SAME file as our JS-side TRACE_FILE — so [native] and [audio]
// lines interleave naturally with the [js] lines below.

// Crash-resilient logger: writes every step to disk so that, even if the
// process is killed by a native JNI fault, the next launch can show the user
// EXACTLY where the previous run died (no logcat needed).
async function trace(step: string, info: string = ''): Promise<void> {
  lastStep = step;
  const line = `[${new Date().toISOString()}] [js] ${step}${info ? ' :: ' + info : ''}\n`;
  try {
    const existing = (await FileSystem.getInfoAsync(TRACE_FILE)).exists
      ? await FileSystem.readAsStringAsync(TRACE_FILE)
      : '';
    // Cap at 100 KB (we have many more entries now with granular logging).
    const truncated = existing.length > 100_000 ? existing.slice(-50_000) : existing;
    await FileSystem.writeAsStringAsync(TRACE_FILE, truncated + line);
  } catch {
    /* ignore */
  }
  console.log(`[Piper trace] ${line.trim()}`);
}

export async function readPiperTrace(): Promise<string> {
  try {
    const info = await FileSystem.getInfoAsync(TRACE_FILE);
    if (!info.exists) return '(nessun trace registrato)';
    return await FileSystem.readAsStringAsync(TRACE_FILE);
  } catch (e: any) {
    return `(impossibile leggere trace: ${e?.message || e})`;
  }
}

export async function clearPiperTrace(): Promise<void> {
  try { await FileSystem.deleteAsync(TRACE_FILE, { idempotent: true }); } catch { /* ignore */ }
}

// ─── Progress listener (used by Settings/Player UI to show a modal) ─────
export type ProgressInfo = { step: string; percent: number; detail?: string };
type ProgressCallback = (info: ProgressInfo | null) => void;
let progressListener: ProgressCallback | null = null;

export function setPiperProgressListener(cb: ProgressCallback | null): void {
  progressListener = cb;
}

function emitProgress(step: string, percent: number, detail?: string): void {
  try { progressListener?.({ step, percent, detail }); } catch { /* never crash */ }
}

export function getPiperDiagnostics() {
  return { ready, lastError, lastStep, available: isPiperAvailable() };
}

// ─── Friendly error decoder ──────────────────────────────────────────────
// Translates raw sherpa-onnx Kotlin exceptions into actionable Italian text
// so the user can immediately see *why* their model failed and *what* to do.
// Used by Settings UI to show a user-friendly status card.
export type DecodedError = {
  title: string;       // short Italian title shown in the engine card
  detail: string;      // 1-3 line technical detail
  suggestion: string;  // what the user should do next
  category:
    | 'fp16_mismatch'
    | 'quantized'
    | 'missing_op'
    | 'opset_too_new'
    | 'file_corrupt'
    | 'out_of_memory'
    | 'native_missing'
    | 'unknown';
};

export function decodePiperError(raw: string | null | undefined): DecodedError | null {
  if (!raw) return null;
  const msg = String(raw);

  // 1) fp16/float16 type mismatch — model converted to fp16 inconsistently
  if (/tensor\(float16\).*does not match.*tensor\(float\)/i.test(msg) ||
      /Type \(tensor\(float16\)\)/i.test(msg)) {
    return {
      title: 'Modello in FP16 incompatibile',
      detail:
        'Il modello contiene tensori float16 in conflitto con tensori float32 ' +
        'nello stesso grafo. Sherpa-ONNX Piper richiede fp32 puro.',
      suggestion:
        'Riesporta beppe.onnx in fp32 (senza conversione fp16), oppure usa un ' +
        'modello Piper "stock" da huggingface.co/rhasspy/piper-voices/tree/main/it',
      category: 'fp16_mismatch',
    };
  }

  // 2) Quantization mismatch (INT8/INT4 ops not supported)
  if (/QuantizeLinear|DequantizeLinear|QLinearMatMul|QLinearConv|tensor\(int8\)/i.test(msg) ||
      /quantize/i.test(msg)) {
    return {
      title: 'Modello QUANTIZZATO incompatibile',
      detail:
        'Il modello è quantizzato INT8/INT4. Sherpa-ONNX Piper non supporta ' +
        'modelli quantizzati per VITS.',
      suggestion:
        'Riesporta beppe.onnx senza quantizzazione (formato fp32), o usa un ' +
        'modello Piper "stock" da rhasspy/piper-voices.',
      category: 'quantized',
    };
  }

  // 3) Unsupported op (model uses ONNX op not implemented in this onnxruntime build)
  if (/No opset import for domain|Could not find an implementation|not implemented for/i.test(msg)) {
    return {
      title: 'Operazione ONNX non supportata',
      detail:
        'Il modello usa un\'operazione ONNX non implementata in sherpa-onnx 1.12.26.',
      suggestion:
        'Riesporta il modello con --opset_version 14 (più conservativo) o usa ' +
        'un modello Piper "stock".',
      category: 'missing_op',
    };
  }

  // 4) Opset too new
  if (/opset.*too new|unsupported opset/i.test(msg)) {
    return {
      title: 'Versione ONNX troppo recente',
      detail: 'Il modello usa un opset_version superiore a quello supportato.',
      suggestion: 'Riesporta con --opset_version 14 oppure 15.',
      category: 'opset_too_new',
    };
  }

  // 5) Corrupted file / not a valid ONNX
  if (/Protobuf parsing failed|invalid model|corrupted|truncated/i.test(msg)) {
    return {
      title: 'File del modello corrotto',
      detail: 'Il file beppe.onnx non è un ONNX valido (parsing protobuf fallito).',
      suggestion: 'Ricopia il modello in frontend/assets/piper/ e ricostruisci.',
      category: 'file_corrupt',
    };
  }

  // 6) Out of memory
  if (/out of memory|OOM|allocation failed/i.test(msg)) {
    return {
      title: 'Memoria insufficiente',
      detail: 'Il dispositivo non ha abbastanza RAM libera per caricare il modello.',
      suggestion: 'Chiudi altre app, oppure usa un modello Piper più piccolo (low/medium).',
      category: 'out_of_memory',
    };
  }

  // 7) Native module not available (Expo Go preview)
  if (/native.*not available|TTSManager.*missing|Modulo nativo/i.test(msg)) {
    return {
      title: 'Modulo nativo mancante',
      detail: 'Stai usando Expo Go o una build di preview senza il modulo Sherpa-ONNX.',
      suggestion: 'Crea un build EAS: eas build --platform android --profile preview',
      category: 'native_missing',
    };
  }

  // Unknown error
  return {
    title: 'Errore TTS sconosciuto',
    detail: msg.length > 200 ? msg.slice(0, 200) + '…' : msg,
    suggestion: 'Apri DIAGNOSTICA PIPER e copia il trace per analisi.',
    category: 'unknown',
  };
}

// ─── System info dump for diagnostics ────────────────────────────────────
async function logSystemInfo(): Promise<void> {
  try {
    const brand = Device.brand || 'unknown';
    const modelName = Device.modelName || 'unknown';
    const osName = Device.osName || Platform.OS;
    const osVersion = Device.osVersion || 'unknown';
    const totalMemMB = Math.round((Device.totalMemory || 0) / (1024 * 1024));
    const isDevice = Device.isDevice;
    const supportedCpuArchitectures = (Device as any).supportedCpuArchitectures?.join(',') || 'unknown';
    await trace('sysinfo',
      `brand=${brand} model=${modelName} os=${osName}/${osVersion} mem=${totalMemMB}MB isDevice=${isDevice} arch=${supportedCpuArchitectures}`);
    await trace('sysinfo.expo',
      `expo=${Constants.expoConfig?.version || '?'} sdk=${Constants.expoConfig?.sdkVersion || '?'}`);
    await trace('sysinfo.paths',
      `docDir=${FileSystem.documentDirectory} cacheDir=${FileSystem.cacheDirectory}`);
  } catch (e: any) {
    await trace('sysinfo.err', `${e?.message || e}`);
  }
}

// ─── File integrity helpers (used by initEngine + runFullDiagnostics) ────
export type OnnxHeaderInfo = {
  ok: boolean;
  hex: string;
  sizeBytes: number;
  irVersion?: number;
  producerName?: string;
  producerVersion?: string;
  isQuantized: boolean;
  quantizationHint?: string;
};

// Parse the first ~256 bytes of an ONNX file to extract metadata fields
// (ir_version, producer_name, producer_version) using a minimal protobuf
// decoder. This lets the diagnostics screen detect:
//   - quantized models (producer_name contains "quantize" or similar)
//   - unusual exporters (e.g. custom optimization scripts)
//   - very new exports (e.g. PyTorch 2.x ops not supported by old sherpa)
async function verifyOnnxMagic(modelPath: string): Promise<OnnxHeaderInfo> {
  try {
    const info = await FileSystem.getInfoAsync(modelPath, { size: true } as any);
    if (!info.exists) {
      return { ok: false, hex: '(missing)', sizeBytes: 0, isQuantized: false };
    }
    // Read enough to grab ir_version + producer_name + producer_version.
    const head = await FileSystem.readAsStringAsync(modelPath, {
      encoding: FileSystem.EncodingType.Base64, length: 256, position: 0,
    } as any);
    const bytes = new Uint8Array(Buffer.from(head, 'base64'));
    const hex = Array.from(bytes.slice(0, 16))
      .map((b) => b.toString(16).padStart(2, '0'))
      .join(' ');

    // ─── Minimal protobuf parser for ModelProto header ─────────────────
    // Wire format: tag = (field_num << 3) | wire_type
    //   field 1: ir_version           (varint)         tag=0x08
    //   field 2: producer_name        (length-delim)   tag=0x12
    //   field 3: producer_version     (length-delim)   tag=0x1a
    //   field 4: domain               (length-delim)   tag=0x22
    //   field 5: model_version        (varint)         tag=0x28
    let pos = 0;
    let irVersion: number | undefined;
    let producerName: string | undefined;
    let producerVersion: string | undefined;

    const readVarint = (): number => {
      let val = 0;
      let shift = 0;
      while (pos < bytes.length) {
        const b = bytes[pos++];
        val |= (b & 0x7f) << shift;
        if ((b & 0x80) === 0) return val;
        shift += 7;
        if (shift >= 35) break; // sanity bound
      }
      return val;
    };

    const readLengthDelim = (): string => {
      const len = readVarint();
      if (len <= 0 || pos + len > bytes.length) return '';
      const slice = bytes.slice(pos, pos + len);
      pos += len;
      // ASCII / UTF-8 to string
      let s = '';
      for (let i = 0; i < slice.length; i++) s += String.fromCharCode(slice[i]);
      return s;
    };

    // Parse first ~4 fields
    try {
      while (pos < bytes.length && pos < 200) {
        const tag = bytes[pos++];
        if (tag === 0x08) {
          irVersion = readVarint();
        } else if (tag === 0x12) {
          producerName = readLengthDelim();
        } else if (tag === 0x1a) {
          producerVersion = readLengthDelim();
        } else if (tag === 0x22) {
          // domain — skip
          const len = readVarint();
          pos += len;
        } else if (tag === 0x28) {
          // model_version varint
          readVarint();
        } else {
          // Unknown tag — stop parsing (probably entered the graph payload)
          break;
        }
      }
    } catch {
      /* parsing best-effort */
    }

    // Detect quantization from producer name (most reliable hint without
    // walking the full graph).
    const producerLower = (producerName || '').toLowerCase();
    let isQuantized = false;
    let quantizationHint: string | undefined;
    if (/quant/.test(producerLower)) {
      isQuantized = true;
      quantizationHint = `producer "${producerName}" indica quantizzazione (INT8/INT4)`;
    } else if (/int8|qdq|qoperator/.test(producerLower)) {
      isQuantized = true;
      quantizationHint = `producer "${producerName}" suggerisce quantizzazione`;
    } else if ((info as any).size && (info as any).size < 30 * 1024 * 1024 &&
               /pytorch/.test(producerLower)) {
      // Standard Piper Italian "medium" is ~64MB, "low" ~28MB. Below 30MB
      // for a PyTorch export is suspicious — flag as POSSIBLY quantized.
      isQuantized = false;
      quantizationHint = `dimensione ${Math.round((info as any).size / 1024 / 1024)}MB inferiore ai Piper standard — possibilmente quantizzato o low-quality`;
    }

    return {
      ok: bytes[0] === 0x08,
      hex,
      sizeBytes: (info as any).size || 0,
      irVersion,
      producerName,
      producerVersion,
      isQuantized,
      quantizationHint,
    };
  } catch (e: any) {
    return {
      ok: false,
      hex: `(err: ${e?.message || e})`,
      sizeBytes: 0,
      isQuantized: false,
    };
  }
}

async function countDirEntries(dirPath: string): Promise<number> {
  try {
    const entries = await FileSystem.readDirectoryAsync(dirPath);
    return entries.length;
  } catch {
    return -1;
  }
}

async function ensureDir(path: string): Promise<void> {
  const info = await FileSystem.getInfoAsync(path);
  if (!info.exists) {
    await FileSystem.makeDirectoryAsync(path, { intermediates: true });
  }
}

async function copyAsset(modId: number, destName: string): Promise<string> {
  const dest = `${DEST_DIR}/${destName}`;
  const info = await FileSystem.getInfoAsync(dest);
  if (info.exists) {
    await trace(`copy.${destName}.skip`, 'already exists');
    return dest;
  }
  await trace(`copy.${destName}.resolve`, 'Asset.fromModule()...');
  const asset = Asset.fromModule(modId);
  await trace(`copy.${destName}.download`, 'asset.downloadAsync()...');
  await asset.downloadAsync();
  const src = asset.localUri || asset.uri;
  if (!src) throw new Error(`Asset ${destName} ha localUri vuoto`);
  await trace(`copy.${destName}.src`, `src=${src.slice(0, 120)}`);
  await trace(`copy.${destName}.copy`, `-> ${dest.slice(0, 120)}`);
  await FileSystem.copyAsync({ from: src, to: dest });
  await trace(`copy.${destName}.ok`, 'done');
  return dest;
}

async function unzipEspeak(modId: number): Promise<string> {
  const dataDir = `${DEST_DIR}/espeak-ng-data`;
  const marker = `${DEST_DIR}/.espeak-ready`;
  await trace('espeak.check', 'checking for ready marker...');
  const dirInfo = await FileSystem.getInfoAsync(dataDir);
  const markerInfo = await FileSystem.getInfoAsync(marker);
  if (dirInfo.exists && dirInfo.isDirectory && markerInfo.exists) {
    const entryCount = await countDirEntries(dataDir);
    await trace('espeak.skip', `already extracted, entries=${entryCount}`);
    return dataDir;
  }
  if (dirInfo.exists) {
    await trace('espeak.cleanup', 'partial dir detected, deleting...');
    try { await FileSystem.deleteAsync(dataDir, { idempotent: true }); } catch { /* ignore */ }
  }

  await trace('espeak.resolve', 'Asset.fromModule()...');
  const asset = Asset.fromModule(modId);
  await asset.downloadAsync();
  const src = asset.localUri || asset.uri;
  if (!src) throw new Error('espeak-ng-data.bin: localUri vuoto');
  await trace('espeak.src', `src=${src.slice(0, 120)}`);

  await trace('espeak.read.b64', 'reading zip as base64...');
  const b64 = await FileSystem.readAsStringAsync(src, { encoding: FileSystem.EncodingType.Base64 });
  await trace('espeak.read.b64.ok', `len=${b64.length} bytes (base64)`);

  await trace('espeak.decode', 'base64 -> Uint8Array...');
  const bytes = new Uint8Array(Buffer.from(b64, 'base64'));
  await trace('espeak.decode.ok', `size=${bytes.length} bytes`);

  // Verify ZIP magic
  const zipMagic = `${bytes[0].toString(16)} ${bytes[1].toString(16)} ${bytes[2].toString(16)} ${bytes[3].toString(16)}`;
  await trace('espeak.zip.magic', `head=${zipMagic} (expect 50 4b 3 4 = PK\\x03\\x04)`);

  await trace('espeak.unzip', 'unzipSync()...');
  const entries = unzipSync(bytes);
  const totalEntries = Object.keys(entries).length;
  await trace('espeak.unzip.ok', `${totalEntries} entries`);

  let count = 0;
  for (const [name, data] of Object.entries(entries)) {
    const fullPath = `${DEST_DIR}/${name}`;
    if (name.endsWith('/') || data.length === 0) {
      await ensureDir(fullPath);
      continue;
    }
    const parent = fullPath.replace(/\/[^/]+$/, '');
    await ensureDir(parent);
    const out64 = Buffer.from(data).toString('base64');
    await FileSystem.writeAsStringAsync(fullPath, out64, { encoding: FileSystem.EncodingType.Base64 });
    count += 1;
    if (count % 50 === 0) {
      await trace('espeak.write.progress', `${count}/${totalEntries}`);
      await new Promise<void>((r) => setTimeout(r, 0));
    }
  }
  await FileSystem.writeAsStringAsync(marker, String(count), { encoding: FileSystem.EncodingType.UTF8 });
  await trace('espeak.complete', `wrote ${count} files, marker created`);
  return dataDir;
}

function stripFilePrefix(p: string): string {
  return p.startsWith('file://') ? p.slice(7) : p;
}

export async function initEngine(): Promise<boolean> {
  if (initPromise) return initPromise;
  initPromise = (async () => {
    await trace('==INIT.START==', `sample_rate=${PIPER_SAMPLE_RATE}`);
    emitProgress('Avvio motore TTS...', 1);
    await logSystemInfo();

    if (!isPiperAvailable()) {
      lastError = 'Modulo nativo Sherpa non disponibile (anteprima Expo Go)';
      await trace('check-native', 'FAIL: TTSManager non in NativeModules');
      emitProgress('Modulo nativo non disponibile', 0, lastError);
      return false;
    }
    const nm: any = (NativeModules as any).TTSManager;
    await trace('check-native', `OK module=${typeof nm} hasInit=${typeof nm?.initializeTTS}`);

    try {
      await trace('mkdir', `path=${DEST_DIR}`);
      await ensureDir(DEST_DIR);
      await trace('mkdir.ok', 'directory ensured');

      emitProgress('Copia del modello vocale...', 5, '108 MB');
      await trace('==PHASE.1==', 'copy beppe.onnx');
      const modelPathU = await copyAsset(PIPER_ASSETS.model, 'beppe.onnx');
      const modelStat = await FileSystem.getInfoAsync(modelPathU, { size: true } as any);
      await trace('phase1.done', `path=${modelPathU} size=${(modelStat as any).size || 0}B`);
      emitProgress('Modello copiato', 15);

      await trace('==PHASE.2==', 'copy tokens.txt');
      const tokensPathU = await copyAsset(PIPER_ASSETS.tokens, 'tokens.txt');
      const tokensStat = await FileSystem.getInfoAsync(tokensPathU, { size: true } as any);
      await trace('phase2.done', `path=${tokensPathU} size=${(tokensStat as any).size || 0}B`);
      emitProgress('Token vocali pronti', 20);

      emitProgress('Estrazione dizionari fonetici...', 25, 'può richiedere 10-30s al primo avvio');
      await trace('==PHASE.3==', 'extract espeak-ng-data (può richiedere 10-30s)');
      const dataDirPathU = await unzipEspeak(PIPER_ASSETS.espeakZip);
      const dataDirStat = await FileSystem.getInfoAsync(dataDirPathU);
      const espeakCount = await countDirEntries(dataDirPathU);
      await trace('phase3.done', `path=${dataDirPathU} isDir=${dataDirStat.isDirectory} entries=${espeakCount}`);
      emitProgress('Dizionari fonetici pronti', 45);

      const modelPath = stripFilePrefix(modelPathU);
      const tokensPath = stripFilePrefix(tokensPathU);
      const dataDirPath = stripFilePrefix(dataDirPathU);

      emitProgress('Verifica integrità modello...', 48);
      await trace('==PHASE.4==', 'verify ONNX magic bytes + producer name + quantization');
      const magic = await verifyOnnxMagic(modelPathU);
      await trace('phase4.magic',
        `head=${magic.hex} ir=${magic.irVersion ?? '?'} ` +
        `producer="${magic.producerName ?? '?'}" version="${magic.producerVersion ?? '?'}" ` +
        `size=${magic.sizeBytes}B validMagic=${magic.ok} quantized=${magic.isQuantized}`);

      if (!magic.ok) {
        await trace('phase4.WARN', 'first byte != 0x08 (not standard ONNX protobuf)');
      }

      // ─── HARD STOP for quantized models ─────────────────────────────
      // sherpa-onnx 1.12.26's Piper pipeline expects fp32/fp16 tensors and
      // does NOT support INT8/INT4 quantized Piper VITS models. Attempting
      // to load one causes a SIGSEGV inside libonnxruntime.so during model
      // initialization, which kills the entire process (uncatchable from
      // Java/Kotlin). To avoid this confusing crash, we detect quantization
      // here in JS and refuse to call native init.
      if (magic.isQuantized) {
        const msg =
          'Il modello beppe.onnx è QUANTIZZATO (INT8/INT4) e non è ' +
          'supportato da sherpa-onnx per Piper TTS. Devi usare un modello ' +
          'in formato fp32 (o fp16). Vedi Diagnostica Piper → ' +
          'NotQuantized per i dettagli, oppure scarica un modello "stock" ' +
          'da rhasspy/piper-voices.';
        await trace('phase4.QUANTIZED_REJECT', magic.quantizationHint || msg);
        throw new Error(msg);
      }

      await trace('==PHASE.5==', 'final sanity checks');
      if (!modelStat.exists || !(modelStat as any).size) {
        throw new Error(`modello mancante o vuoto: ${modelPath}`);
      }
      if (!tokensStat.exists || !(tokensStat as any).size) {
        throw new Error(`tokens.txt mancante o vuoto: ${tokensPath}`);
      }
      if (!dataDirStat.exists || !dataDirStat.isDirectory) {
        throw new Error(`espeak-ng-data non è una directory: ${dataDirPath}`);
      }
      if (espeakCount < 10) {
        throw new Error(`espeak-ng-data ha solo ${espeakCount} file (estrazione fallita?)`);
      }
      const espeakEntries = await FileSystem.readDirectoryAsync(dataDirPathU);
      const hasPhontab = espeakEntries.includes('phontab');
      const hasPhonindex = espeakEntries.includes('phonindex');
      const hasLang = espeakEntries.includes('lang');
      await trace('phase5.espeak.files',
        `phontab=${hasPhontab} phonindex=${hasPhonindex} lang=${hasLang} first10=${espeakEntries.slice(0, 10).join(',')}`);
      if (!hasPhontab || !hasPhonindex) {
        await trace('phase5.WARN', 'missing canonical espeak files');
      }
      emitProgress('File verificati', 55);

      emitProgress('Caricamento modello in memoria...', 60, 'modello da 108 MB, attendere 10-30s');
      await trace('==PHASE.6==', 'invoke native initializeTTS (può richiedere 10-60s per modelli grandi)');
      await trace('phase6.args',
        `sr=${PIPER_SAMPLE_RATE} ch=1 modelPath=${modelPath} tokensPath=${tokensPath} dataDirPath=${dataDirPath}`);
      const tts = getSherpaTTS()!;
      const cfg = { modelPath, tokensPath, dataDirPath };

      // ─── CRITICAL FIX: actually await the native promise ───────────────
      // The patched Kotlin initializeTTS now ACCEPTS a Promise parameter
      // and runs the heavy model load on a background thread. JS must
      // ACTUALLY await this — otherwise we race ahead and call speak()
      // while the engine is still loading.
      //
      // No JS-side timeout: as the user pointed out, the first launch may
      // legitimately need ~30-60s on slower devices. We TRUST the native
      // side to either succeed or reject. If native hangs, the user can
      // close the app — the next launch will see ready=false and retry.
      await new Promise<void>((resolve, reject) => {
        const native: any = (NativeModules as any).TTSManager;
        if (!native || typeof native.initializeTTS !== 'function') {
          reject(new Error('Native TTSManager.initializeTTS missing'));
          return;
        }
        // Heartbeat: every 2s while we wait, update the progress UI so
        // the user sees we're still alive (not frozen).
        let elapsedSec = 0;
        const heartbeat = setInterval(() => {
          elapsedSec += 2;
          emitProgress(
            'Caricamento modello in memoria...',
            Math.min(85, 60 + Math.floor(elapsedSec / 2)),
            `${elapsedSec}s trascorsi (atteso 10-60s)`
          );
        }, 2000);

        const p = native.initializeTTS(PIPER_SAMPLE_RATE, 1, JSON.stringify(cfg));
        if (p && typeof p.then === 'function') {
          p.then(
            (result: any) => {
              clearInterval(heartbeat);
              trace('phase6.native.resolve', `result=${result}`);
              resolve();
            },
            (err: any) => {
              clearInterval(heartbeat);
              trace('phase6.native.reject', `${err?.message || err}`);
              reject(err);
            }
          );
        } else {
          clearInterval(heartbeat);
          trace('phase6.WARN', 'native did not return promise — using fallback delay');
          // No promise from native (old patch?) — wait a reasonable time
          // and hope for the best.
          setTimeout(() => resolve(), 30_000);
        }
      });
      await trace('phase6.done', 'native initializeTTS resolved promise (FULL init complete)');
      emitProgress('Test rapido voce...', 90);

      ready = true;
      lastError = null;
      await trace('==INIT.READY==', 'TTS engine pronto');
      emitProgress('Voce pronta!', 100);
      // Give the UI a moment to show the "Pronta" status before clearing
      setTimeout(() => emitProgress('', 0), 1500);
      return true;
    } catch (e: any) {
      ready = false;
      lastError = `${lastStep}: ${e?.message || String(e)}`;
      await trace('==INIT.ERROR==', `at step=${lastStep}: ${e?.message || String(e)}`);
      emitProgress('Errore caricamento', 0, e?.message || String(e));
      return false;
    }
  })();
  return initPromise;
}

// ─── Diagnostic-only function (does NOT actually init TTS) ───────────────
// Performs all the file checks and reports a status object that can be
// rendered in the Settings panel. Useful for troubleshooting WITHOUT
// triggering a potentially-crashing native call.
export type DiagnosticItem = { name: string; ok: boolean; detail: string };

export async function runFullDiagnostics(): Promise<DiagnosticItem[]> {
  const results: DiagnosticItem[] = [];
  const push = async (name: string, ok: boolean, detail: string) => {
    results.push({ name, ok, detail });
    await trace(`diag.${name}`, `ok=${ok} ${detail}`);
  };

  await trace('==DIAGNOSTICS.START==', '');

  // 1. Platform
  await push('Platform',
    Platform.OS === 'android' || Platform.OS === 'ios',
    `OS=${Platform.OS} ver=${Platform.Version}`);

  // 2. Device info
  await push('Device',
    !!Device.brand,
    `${Device.brand || '?'} ${Device.modelName || '?'} mem=${Math.round((Device.totalMemory || 0) / (1024 * 1024))}MB`);

  // 3. Native module presence
  const nm: any = (NativeModules as any).TTSManager;
  await push('NativeModule',
    !!nm && typeof nm.initializeTTS === 'function',
    `TTSManager=${!!nm} hasInit=${typeof nm?.initializeTTS}`);

  // 4. DEST_DIR exists
  const destInfo = await FileSystem.getInfoAsync(DEST_DIR);
  await push('DestDir', destInfo.exists, `${DEST_DIR} exists=${destInfo.exists}`);

  // 5. Model file
  const modelPath = `${DEST_DIR}/beppe.onnx`;
  const modelInfo = await FileSystem.getInfoAsync(modelPath, { size: true } as any);
  const modelSize = (modelInfo as any).size || 0;
  await push('Model', modelInfo.exists && modelSize > 1_000_000,
    `${modelPath} exists=${modelInfo.exists} size=${modelSize}B (${(modelSize / 1024 / 1024).toFixed(1)}MB)`);

  // 6. ONNX magic + producer name + quantization detector
  if (modelInfo.exists) {
    const magic = await verifyOnnxMagic(modelPath);
    await push('OnnxMagic', magic.ok,
      `head=${magic.hex} ir=${magic.irVersion ?? '?'} valid=${magic.ok}`);

    // 6b. Producer name (huge clue about compatibility)
    const producerLabel = magic.producerName
      ? `${magic.producerName}${magic.producerVersion ? ' ' + magic.producerVersion : ''}`
      : '(producer non rilevato)';
    // Standard Piper models have producer "pytorch". Anything else is unusual.
    const isStandardPiper = !!(magic.producerName &&
      /pytorch/i.test(magic.producerName) && !magic.isQuantized);
    await push('ModelFormat', isStandardPiper, producerLabel);

    // 6c. Quantization warning — this is the SINGLE most important check
    // for diagnosing the SIGSEGV on this device.
    if (magic.isQuantized) {
      await push(
        'NotQuantized',
        false,
        `⚠ MODELLO QUANTIZZATO: ${magic.quantizationHint}. ` +
        `sherpa-onnx Piper NON supporta i modelli INT8/INT4 quantizzati: ` +
        `richiede fp32 (o fp16). Riesporta beppe.onnx senza --quantize, ` +
        `oppure usa un modello Piper "stock" da rhasspy/piper-voices.`
      );
    } else if (magic.quantizationHint) {
      // Suspicious but not confirmed
      await push('NotQuantized', false, `⚠ ${magic.quantizationHint}`);
    } else {
      await push('NotQuantized', true,
        `formato standard, dim=${(magic.sizeBytes / 1024 / 1024).toFixed(1)}MB`);
    }
  } else {
    await push('OnnxMagic', false, '(skipped: model not copied yet)');
    await push('ModelFormat', false, '(skipped: model not copied yet)');
    await push('NotQuantized', false, '(skipped: model not copied yet)');
  }

  // 7. Tokens file
  const tokensPath = `${DEST_DIR}/tokens.txt`;
  const tokensInfo = await FileSystem.getInfoAsync(tokensPath, { size: true } as any);
  await push('Tokens', tokensInfo.exists && (tokensInfo as any).size > 0,
    `${tokensPath} exists=${tokensInfo.exists} size=${(tokensInfo as any).size || 0}B`);

  // 8. Espeak directory + content
  const espeakDir = `${DEST_DIR}/espeak-ng-data`;
  const espeakInfo = await FileSystem.getInfoAsync(espeakDir);
  await push('EspeakDir', espeakInfo.exists && espeakInfo.isDirectory,
    `${espeakDir} exists=${espeakInfo.exists} isDir=${espeakInfo.isDirectory}`);

  if (espeakInfo.exists && espeakInfo.isDirectory) {
    const entries = await FileSystem.readDirectoryAsync(espeakDir);
    const hasPhontab = entries.includes('phontab');
    const hasPhonindex = entries.includes('phonindex');
    await push('EspeakFiles',
      entries.length >= 10 && hasPhontab && hasPhonindex,
      `entries=${entries.length} phontab=${hasPhontab} phonindex=${hasPhonindex}`);
  } else {
    await push('EspeakFiles', false, '(skipped: dir missing)');
  }

  // 9. Trace file size
  const traceInfo = await FileSystem.getInfoAsync(TRACE_FILE, { size: true } as any);
  await push('TraceFile', true,
    `${TRACE_FILE} exists=${traceInfo.exists} size=${(traceInfo as any).size || 0}B`);

  // 10. Engine state
  await push('EngineState', true,
    `ready=${ready} lastError=${lastError || 'none'} lastStep=${lastStep}`);

  await trace('==DIAGNOSTICS.END==', `${results.length} checks ${results.filter(r => r.ok).length} ok`);
  return results;
}

export function isPiperReady(): boolean {
  return ready;
}

// Sanitize a sentence before sending to Sherpa-ONNX.
function sanitizeForPiper(raw: string): string {
  return raw
    .replace(/(\p{L})-(\p{L})/gu, '$1 $2')
    .replace(/\s*[—–]\s*/g, ', ')
    .replace(/[\u0000-\u001F\u007F]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

export async function speakSentence(text: string, lengthScale: number): Promise<void> {
  const tts = getSherpaTTS();
  if (!tts || !ready) {
    await trace('speak.skip', 'Piper not available');
    throw new Error('Piper not available');
  }
  const speed = Math.max(0.5, Math.min(2.0, 1 / lengthScale));
  const clean = sanitizeForPiper(text);
  if (!clean) {
    await trace('speak.skip', 'empty after sanitize');
    return;
  }
  const preview = clean.slice(0, 80);
  try {
    await trace('speak.start', `len=${clean.length} speed=${speed.toFixed(2)} preview="${preview}"`);
    await tts.generateAndPlay(clean, 0, speed);
    await trace('speak.end', 'OK');
  } catch (e: any) {
    await trace('speak.error', `${e?.message || String(e)}`);
    throw e;
  }
}

export async function stopSpeak(): Promise<void> {
  const tts = getSherpaTTS();
  if (!tts) return;
  // PATCH (beppe-audiobooks v5): use the NEW native stopPlayback() method
  // which only aborts the current sentence's audio output. The previous
  // implementation called deinitialize(), which destroyed the entire
  // sherpa-onnx engine + AudioTrack. JS then re-initialized in the
  // background — but a concurrent play() would race ahead and find
  // ready=false, so the device's stock TTS spoke instead. This is the
  // root cause of "after I press stop, the device voice comes out".
  const native: any = (NativeModules as any).TTSManager;
  if (native && typeof native.stopPlayback === 'function') {
    try {
      await trace('stop.call', 'stopPlayback (engine preserved)');
      await native.stopPlayback();
      await trace('stop.call', 'OK');
    } catch (e: any) {
      await trace('stop.call', `err: ${e?.message || e}`);
    }
    // CRITICAL: do NOT clear `ready` or `initPromise` here. The engine is
    // still loaded; the next speak() can resume instantly with Piper.
    return;
  }
  // Fallback path (for an older patch without stopPlayback): use the
  // legacy hard-reset.
  try {
    await trace('stop.call', 'deinitialize (legacy fallback)');
    await tts.deinitialize();
    await trace('stop.call', 'OK');
  } catch (e: any) {
    await trace('stop.call', `err: ${e?.message || e}`);
  }
  ready = false;
  initPromise = null;
  initEngine();
}

// ─── PATCH (beppe-audiobooks v6): foreground service / MediaSession ────
//
// Lightweight wrappers around the three native methods exposed by the
// updated TTSManagerModule. They are no-ops if the running native module
// does not implement them (so the JS bundle stays compatible with older
// patches).

export type PlaybackSession = {
  title: string;
  author?: string | null;
  coverBase64?: string | null; // can be raw base64 or "data:image/...;base64,...."
  isPlaying: boolean;
};

export async function startPlaybackSession(s: PlaybackSession): Promise<void> {
  const native: any = (NativeModules as any).TTSManager;
  if (!native || typeof native.startPlaybackSession !== 'function') return;
  try {
    await native.startPlaybackSession({
      title: s.title || 'Audiobook',
      author: s.author || '',
      coverBase64: s.coverBase64 || null,
      isPlaying: !!s.isPlaying,
    });
  } catch (e: any) {
    await trace('playback.session.start.JS', `err: ${e?.message || e}`);
  }
}

export async function updatePlaybackSession(s: Partial<PlaybackSession>): Promise<void> {
  const native: any = (NativeModules as any).TTSManager;
  if (!native || typeof native.updatePlaybackSession !== 'function') return;
  try {
    await native.updatePlaybackSession({
      title: s.title ?? 'Audiobook',
      author: s.author ?? '',
      coverBase64: s.coverBase64 ?? null,
      isPlaying: typeof s.isPlaying === 'boolean' ? s.isPlaying : true,
    });
  } catch (e: any) {
    await trace('playback.session.update.JS', `err: ${e?.message || e}`);
  }
}

export async function stopPlaybackSession(): Promise<void> {
  const native: any = (NativeModules as any).TTSManager;
  if (!native || typeof native.stopPlaybackSession !== 'function') return;
  try {
    await native.stopPlaybackSession();
  } catch (e: any) {
    await trace('playback.session.stop.JS', `err: ${e?.message || e}`);
  }
}

export const piperPlatformOk = Platform.OS === 'android' || Platform.OS === 'ios';
