// On-device Piper TTS engine using react-native-sherpa-onnx-offline-tts.
// Real-time, offline, no server. Assets are pre-bundled in the APK.
//
// The bundled beppe.onnx MUST be the version produced by
// scripts/prepare_piper_model.py — i.e., a Piper .onnx with sherpa-onnx
// metadata injected (model_type=vits, comment=piper, has_espeak=1, ...).
// Without those metadata sherpa-onnx will refuse to load the model.
//
// At first launch:
//   1) Copy beppe.onnx + tokens.txt to documents/piper/
//   2) Unzip espeak-ng-data.bin → documents/piper/espeak-ng-data/
//   3) Init sherpa-onnx with full OfflineTtsConfig
import { Asset } from 'expo-asset';
import * as FileSystem from 'expo-file-system/legacy';
import { unzipSync } from 'fflate';
import { NativeModules, Platform } from 'react-native';
import { Buffer } from 'buffer';
import { PIPER_ASSETS } from './piperAssets';
import { getSherpaTTS, isPiperAvailable } from './sherpaPiper';
// Runtime config generated by scripts/prepare_piper_model.py from the
// model's .onnx.json. Single source of truth for the sample rate so the
// native AudioTrack matches the Piper model exactly (16000 / 22050 / etc.).
// eslint-disable-next-line @typescript-eslint/no-require-imports
const PIPER_CONFIG: { sample_rate: number; language?: string; voice?: string; n_speakers?: number } =
  require('../../assets/piper/piper-config.json');
const PIPER_SAMPLE_RATE = PIPER_CONFIG.sample_rate || 22050;

let initPromise: Promise<boolean> | null = null;
let ready = false;
let lastError: string | null = null;
let lastStep: string = 'idle';

const DEST_DIR = `${FileSystem.documentDirectory}piper`;
const TRACE_FILE = `${FileSystem.documentDirectory}piper-trace.log`;

// Crash-resilient logger: writes every step to disk so that, even if the
// process is killed by a native JNI fault, the next launch can show the user
// EXACTLY where the previous run died (no logcat needed).
async function trace(step: string, info: string = ''): Promise<void> {
  lastStep = step;
  const line = `[${new Date().toISOString()}] ${step}${info ? ' :: ' + info : ''}\n`;
  // Best-effort, never throws.
  try {
    const existing = (await FileSystem.getInfoAsync(TRACE_FILE)).exists
      ? await FileSystem.readAsStringAsync(TRACE_FILE)
      : '';
    // Keep file from growing unbounded (cap ~50 KB).
    const truncated = existing.length > 50_000 ? existing.slice(-25_000) : existing;
    await FileSystem.writeAsStringAsync(TRACE_FILE, truncated + line);
  } catch {
    /* ignore — disk may be full or perms denied */
  }
  console.log(`[Piper trace] ${line.trim()}`);
}

export async function readPiperTrace(): Promise<string> {
  try {
    const info = await FileSystem.getInfoAsync(TRACE_FILE);
    if (!info.exists) return '(nessun trace registrato)';
    return await FileSystem.readAsStringAsync(TRACE_FILE);
  } catch (e: any) {
    return `(impossibile leggere trace: ${e?.message || e})`;
  }
}

export async function clearPiperTrace(): Promise<void> {
  try { await FileSystem.deleteAsync(TRACE_FILE, { idempotent: true }); } catch { /* ignore */ }
}

export function getPiperDiagnostics() {
  return { ready, lastError, lastStep, available: isPiperAvailable() };
}

async function ensureDir(path: string): Promise<void> {
  const info = await FileSystem.getInfoAsync(path);
  if (!info.exists) {
    await FileSystem.makeDirectoryAsync(path, { intermediates: true });
  }
}

async function copyAsset(modId: number, destName: string): Promise<string> {
  const dest = `${DEST_DIR}/${destName}`;
  const info = await FileSystem.getInfoAsync(dest);
  if (info.exists) return dest;
  const asset = Asset.fromModule(modId);
  await asset.downloadAsync();
  const src = asset.localUri || asset.uri;
  if (!src) throw new Error(`Asset ${destName} ha localUri vuoto`);
  await FileSystem.copyAsync({ from: src, to: dest });
  return dest;
}

async function unzipEspeak(modId: number): Promise<string> {
  const dataDir = `${DEST_DIR}/espeak-ng-data`;
  const marker = `${DEST_DIR}/.espeak-ready`;

  // Only trust the dir if the completion marker exists (avoids partial state
  // from a previous app crash during unzip).
  const dirInfo = await FileSystem.getInfoAsync(dataDir);
  const markerInfo = await FileSystem.getInfoAsync(marker);
  if (dirInfo.exists && dirInfo.isDirectory && markerInfo.exists) {
    return dataDir;
  }
  // Clean up any partial extraction.
  if (dirInfo.exists) {
    try { await FileSystem.deleteAsync(dataDir, { idempotent: true }); } catch { /* ignore */ }
  }

  const asset = Asset.fromModule(modId);
  await asset.downloadAsync();
  const src = asset.localUri || asset.uri;
  if (!src) throw new Error('espeak-ng-data.bin: localUri vuoto');
  const b64 = await FileSystem.readAsStringAsync(src, { encoding: FileSystem.EncodingType.Base64 });
  // Decode base64 → Uint8Array using Buffer polyfill (from 'buffer' package)
  const bytes = new Uint8Array(Buffer.from(b64, 'base64'));
  const entries = unzipSync(bytes);

  let count = 0;
  for (const [name, data] of Object.entries(entries)) {
    const fullPath = `${DEST_DIR}/${name}`;
    if (name.endsWith('/') || data.length === 0) {
      await ensureDir(fullPath);
      continue;
    }
    const parent = fullPath.replace(/\/[^/]+$/, '');
    await ensureDir(parent);
    // Buffer.from is ~10× faster than the manual fromCharCode loop and uses
    // far less peak memory (no giant intermediate JS string).
    const out64 = Buffer.from(data).toString('base64');
    await FileSystem.writeAsStringAsync(fullPath, out64, { encoding: FileSystem.EncodingType.Base64 });
    count += 1;
    // Yield to the event loop every 50 files so the UI thread doesn't ANR.
    if (count % 50 === 0) await new Promise<void>((r) => setTimeout(r, 0));
  }
  // Mark extraction complete so we never read a partial dir on next launch.
  await FileSystem.writeAsStringAsync(marker, String(count), { encoding: FileSystem.EncodingType.UTF8 });
  return dataDir;
}

function stripFilePrefix(p: string): string {
  return p.startsWith('file://') ? p.slice(7) : p;
}

export async function initEngine(): Promise<boolean> {
  if (initPromise) return initPromise;
  initPromise = (async () => {
    await trace('start', `sample_rate=${PIPER_SAMPLE_RATE}`);
    if (!isPiperAvailable()) {
      lastError = 'Modulo nativo Sherpa non disponibile (anteprima Expo Go)';
      await trace('check-native', 'FAIL: TTSManager non in NativeModules');
      return false;
    }
    await trace('check-native', 'OK');
    try {
      await trace('mkdir', `path=${DEST_DIR}`);
      await ensureDir(DEST_DIR);
      await trace('mkdir', 'OK');

      await trace('copy-model', 'inizio');
      const modelPathU = await copyAsset(PIPER_ASSETS.model, 'beppe.onnx');
      const modelStat = await FileSystem.getInfoAsync(modelPathU, { size: true } as any);
      await trace('copy-model', `OK size=${(modelStat as any).size || 0} path=${modelPathU}`);

      await trace('copy-tokens', 'inizio');
      const tokensPathU = await copyAsset(PIPER_ASSETS.tokens, 'tokens.txt');
      const tokensStat = await FileSystem.getInfoAsync(tokensPathU, { size: true } as any);
      await trace('copy-tokens', `OK size=${(tokensStat as any).size || 0} path=${tokensPathU}`);

      await trace('unzip-espeak', 'inizio (può richiedere 10-30s)');
      const dataDirPathU = await unzipEspeak(PIPER_ASSETS.espeakZip);
      const dataDirStat = await FileSystem.getInfoAsync(dataDirPathU);
      await trace('unzip-espeak', `OK path=${dataDirPathU} isDir=${dataDirStat.isDirectory}`);

      const modelPath = stripFilePrefix(modelPathU);
      const tokensPath = stripFilePrefix(tokensPathU);
      const dataDirPath = stripFilePrefix(dataDirPathU);

      // Read first 8 bytes of .onnx to verify it's a real ONNX file (not a
      // placeholder/text file). ONNX is a protobuf — first byte is 0x08.
      try {
        const head = await FileSystem.readAsStringAsync(modelPathU, {
          encoding: FileSystem.EncodingType.Base64, length: 16, position: 0,
        } as any);
        const headBytes = Array.from(Buffer.from(head, 'base64')).map(b => b.toString(16).padStart(2, '0')).join(' ');
        await trace('onnx-magic', `first 16 bytes hex: ${headBytes}`);
      } catch (e: any) {
        await trace('onnx-magic', `skip (${e?.message || e})`);
      }

      await trace('sanity-check', 'verifica file');
      if (!modelStat.exists || !(modelStat as any).size) {
        throw new Error(`modello mancante o vuoto: ${modelPath}`);
      }
      if (!tokensStat.exists || !(tokensStat as any).size) {
        throw new Error(`tokens.txt mancante o vuoto: ${tokensPath}`);
      }
      if (!dataDirStat.exists || !dataDirStat.isDirectory) {
        throw new Error(`espeak-ng-data non è una directory: ${dataDirPath}`);
      }
      // Verify at least one espeak file exists inside the data dir.
      const dirEntries = await FileSystem.readDirectoryAsync(dataDirPathU);
      await trace('sanity-check', `espeak-ng-data contiene ${dirEntries.length} entries`);
      if (dirEntries.length < 10) {
        throw new Error(`espeak-ng-data ha solo ${dirEntries.length} file (estrazione fallita?)`);
      }

      await trace('init-sherpa', `cfg={modelPath,tokensPath,dataDirPath} sample_rate=${PIPER_SAMPLE_RATE}`);
      const tts = getSherpaTTS()!;
      const cfg = { modelPath, tokensPath, dataDirPath };

      await new Promise<void>((resolve, reject) => {
        try {
          const native: any = (NativeModules as any).TTSManager;
          let ret: any;
          if (native && typeof native.initializeTTS === 'function') {
            // Direct call — bypasses the wrapper's 22050 default.
            ret = native.initializeTTS(PIPER_SAMPLE_RATE, 1, JSON.stringify(cfg));
          } else {
            ret = (tts as any).initialize(JSON.stringify(cfg));
          }
          if (ret && typeof ret.then === 'function') {
            ret.then(() => resolve(), (err: any) => reject(err));
          } else {
            setTimeout(() => resolve(), 50);
          }
        } catch (err) {
          reject(err);
        }
      });
      await trace('init-sherpa', 'OK (nessuna eccezione JNI sincrona)');

      ready = true;
      lastError = null;
      await trace('ready', 'TTS engine pronto');
      return true;
    } catch (e: any) {
      ready = false;
      lastError = `${lastStep}: ${e?.message || String(e)}`;
      await trace('error', `at step=${lastStep}: ${e?.message || String(e)}`);
      return false;
    }
  })();
  return initPromise;
}

export function isPiperReady(): boolean {
  return ready;
}

// Sanitize a sentence before sending to Sherpa-ONNX.
//
// The Kotlin wrapper (react-native-sherpa-onnx-offline-tts 0.2.6) does a
// blind splitText(text, 15 words) and appends "." to every chunk — which
// creates malformed sequences like ",." that crash espeak-ng's phonemizer
// at the JNI layer (no recoverable exception, app gets SIGKILL'd).
//
// To avoid hitting that code path:
//   1) Split the sentence ourselves into ≤12-word chunks (below the wrapper's
//      15-word threshold so it produces exactly one chunk per chunk we pass).
//   2) Prefer breaking at `; :` > `,` > word boundary.
//   3) Strip any trailing punctuation so the wrapper's "." append is clean.
//   4) Normalize tricky characters that confuse espeak: hyphens inside
//      words, em-dashes, multiple spaces, non-printable chars.
function sanitizeForPiper(raw: string): string[] {
  let text = raw
    // Hyphens between letters (e.g. "re-in-attesa") → spaces
    .replace(/(\p{L})-(\p{L})/gu, '$1 $2')
    // Em/en dashes → comma
    .replace(/[—–]/g, ',')
    // Collapse multiple punctuation marks (",,", ",.", ".," etc.) to a single one
    .replace(/([,.;:!?])\1+/g, '$1')
    .replace(/[,;:]\s*\./g, '.')
    .replace(/\.\s*[,;:]/g, '.')
    // Drop non-printable / control chars
    .replace(/[\u0000-\u001F\u007F]/g, ' ')
    // Collapse whitespace
    .replace(/\s+/g, ' ')
    .trim();

  if (!text) return [];

  // Split into ≤12-word chunks preferring natural punctuation breaks.
  const MAX_WORDS = 12;
  const chunks: string[] = [];
  const words = text.split(' ').filter(Boolean);

  let i = 0;
  while (i < words.length) {
    const end = Math.min(i + MAX_WORDS, words.length);
    // Look backwards from `end` for a "soft break" — punctuation we can cut on
    let cut = -1;
    for (let j = end - 1; j > i; j--) {
      const w = words[j];
      const last = w.slice(-1);
      if (last === ';' || last === ':' || last === ',' || last === '.' || last === '!' || last === '?') {
        cut = j + 1; // include the punctuated word
        break;
      }
    }
    const stop = (cut > 0 && cut > i + 3) ? cut : end;
    let chunk = words.slice(i, stop).join(' ');
    // Strip any trailing punctuation so the wrapper's "." append is clean.
    chunk = chunk.replace(/[,.;:!?]+$/, '').trim();
    if (chunk) chunks.push(chunk);
    i = stop;
  }
  return chunks;
}

export async function speakSentence(text: string, lengthScale: number): Promise<void> {
  const tts = getSherpaTTS();
  if (!tts || !ready) {
    await trace('speak-skip', 'Piper not available');
    throw new Error('Piper not available');
  }
  const speed = Math.max(0.5, Math.min(2.0, 1 / lengthScale));
  const chunks = sanitizeForPiper(text);
  if (!chunks.length) {
    await trace('speak-skip', 'empty after sanitize');
    return;
  }
  for (let i = 0; i < chunks.length; i++) {
    const chunk = chunks[i];
    const preview = chunk.slice(0, 80);
    try {
      await trace('speak-start', `${i + 1}/${chunks.length} len=${chunk.length} speed=${speed.toFixed(2)} preview="${preview}"`);
      await tts.generateAndPlay(chunk, 0, speed);
      await trace('speak-end', `${i + 1}/${chunks.length} OK`);
    } catch (e: any) {
      await trace('speak-error', `${i + 1}/${chunks.length}: ${e?.message || String(e)}`);
      throw e;
    }
  }
}

export async function stopSpeak(): Promise<void> {
  const tts = getSherpaTTS();
  if (!tts) return;
  try {
    await trace('stop-call', 'deinitialize');
    await tts.deinitialize();
    await trace('stop-call', 'OK');
  } catch (e: any) {
    await trace('stop-call', `err: ${e?.message || e}`);
  }
  ready = false;
  initPromise = null;
  initEngine();
}

export const piperPlatformOk = Platform.OS === 'android' || Platform.OS === 'ios';
